import React from 'react';
import { Clock, MapPin, User, Search, HardDrive, Eye, ExternalLink, Download, FileSpreadsheet, Printer } from 'lucide-react';
import { PatrolLog, PatrolStatus } from '../types';
import { GOOGLE_DRIVE_FOLDER_URL } from '../constants';

interface PatrolListProps {
  logs: PatrolLog[];
}

export const PatrolList: React.FC<PatrolListProps> = ({ logs }) => {
  const [searchTerm, setSearchTerm] = React.useState('');

  const filteredLogs = logs.filter(log => 
    log.locationName.toLowerCase().includes(searchTerm.toLowerCase()) || 
    log.guardName.toLowerCase().includes(searchTerm.toLowerCase())
  );

  const handlePrintReport = () => {
     if (filteredLogs.length === 0) {
      alert("Tidak ada data untuk dicetak.");
      return;
    }

    const printWindow = window.open('', '_blank');
    if (!printWindow) return;

    const tableRows = filteredLogs.map((log, index) => `
      <tr>
        <td style="padding: 8px; border: 1px solid #ddd; text-align: center;">${index + 1}</td>
        <td style="padding: 8px; border: 1px solid #ddd;">
          ${new Date(log.timestamp).toLocaleDateString('id-ID')}<br/>
          <span style="font-size: 10px; color: #666;">${new Date(log.timestamp).toLocaleTimeString('id-ID')}</span>
        </td>
        <td style="padding: 8px; border: 1px solid #ddd; text-align: center;">
          ${log.imageUrl ? `<img src="${log.imageUrl}" alt="Eviden" style="width: 80px; height: 80px; object-fit: cover; border-radius: 4px; border: 1px solid #eee;">` : '<span style="color:#ccc;">No Image</span>'}
        </td>
        <td style="padding: 8px; border: 1px solid #ddd;">${log.guardName}</td>
        <td style="padding: 8px; border: 1px solid #ddd;">${log.locationName}</td>
        <td style="padding: 8px; border: 1px solid #ddd;">
          <span style="font-weight: bold; color: ${log.aiAnalysis?.status === PatrolStatus.SECURE ? 'green' : 'red'}">
            ${log.aiAnalysis?.status || 'Manual'}
          </span>
        </td>
        <td style="padding: 8px; border: 1px solid #ddd;">${log.aiAnalysis?.summary || log.notes || '-'}</td>
      </tr>
    `).join('');

    const htmlContent = `
      <html>
        <head>
          <title>Laporan Patroli - SecurePatrol AI</title>
          <style>
            body { font-family: Arial, sans-serif; padding: 20px; }
            h1 { text-align: center; margin-bottom: 5px; }
            p { text-align: center; color: #666; font-size: 14px; margin-top: 0; }
            table { width: 100%; border-collapse: collapse; margin-top: 20px; font-size: 11px; }
            th { background-color: #f2f2f2; font-weight: bold; padding: 10px; border: 1px solid #999; text-align: left; }
            .header-section { margin-bottom: 30px; border-bottom: 2px solid #333; padding-bottom: 20px; }
            .footer { margin-top: 50px; text-align: right; font-size: 12px; }
            @media print {
              tr { page-break-inside: avoid; }
            }
          </style>
        </head>
        <body>
          <div class="header-section">
            <h1>Laporan Patroli Harian</h1>
            <p>Generated by SecurePatrol AI</p>
          </div>

          <table>
            <thead>
              <tr>
                <th style="width: 30px;">No</th>
                <th style="width: 80px;">Waktu</th>
                <th style="width: 90px;">Foto</th>
                <th>Petugas</th>
                <th>Lokasi</th>
                <th>Status</th>
                <th>Keterangan</th>
              </tr>
            </thead>
            <tbody>
              ${tableRows}
            </tbody>
          </table>

          <div class="footer">
            <p>Dicetak pada: ${new Date().toLocaleString('id-ID')}</p>
          </div>
        </body>
      </html>
    `;

    printWindow.document.write(htmlContent);
    printWindow.document.close();
    printWindow.focus();
    setTimeout(() => {
      printWindow.print();
      printWindow.close();
    }, 500);
  };

  const handleExportCSV = () => {
    if (logs.length === 0) {
      alert("Tidak ada data untuk diekspor.");
      return;
    }

    // Define CSV Headers
    const headers = [
      "ID",
      "Tanggal",
      "Waktu",
      "Nama Petugas",
      "Lokasi",
      "Status Keamanan",
      "Catatan/Ringkasan",
      "Latitude",
      "Longitude",
      "Link Foto (Base64)"
    ];

    // Map data to CSV rows
    const rows = logs.map(log => {
      const date = new Date(log.timestamp);
      return [
        `"${log.id}"`,
        `"${date.toLocaleDateString('id-ID')}"`,
        `"${date.toLocaleTimeString('id-ID')}"`,
        `"${log.guardName}"`,
        `"${log.locationName}"`,
        `"${log.aiAnalysis?.status || 'Manual'}"`,
        `"${(log.aiAnalysis?.summary || log.notes || '').replace(/"/g, '""')}"`, // Escape quotes
        `"${log.coordinates?.latitude || ''}"`,
        `"${log.coordinates?.longitude || ''}"`,
        `"Foto Tersimpan di App"` // Too long for CSV usually, better to just indicate existence
      ].join(",");
    });

    const csvContent = [headers.join(","), ...rows].join("\n");
    
    // Create download link
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.setAttribute("download", `Laporan_Patroli_${new Date().toISOString().slice(0,10)}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);

    // Prompt to open Drive
    const shouldOpenDrive = window.confirm(
      "Data berhasil diunduh (Excel/CSV).\n\nApakah Anda ingin membuka Google Drive sekarang untuk mengunggah file ini sebagai backup?"
    );

    if (shouldOpenDrive) {
      window.open(GOOGLE_DRIVE_FOLDER_URL, '_blank');
    }
  };

  return (
    <div className="space-y-4">
      {/* Header & Search */}
      <div className="flex flex-col gap-4 bg-white p-4 rounded-xl shadow-sm border border-slate-200">
        <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
          <div>
             <h2 className="text-lg font-bold text-slate-800 flex items-center gap-2 uppercase tracking-wide">
               <HardDrive size={20} className="text-slate-600" />
               Database Patroli
             </h2>
             <p className="text-xs text-slate-500 font-medium">Rekapitulasi eviden keamanan lokal</p>
          </div>
          
          <div className="flex flex-wrap gap-2 w-full sm:w-auto">
             <button 
              onClick={handlePrintReport}
              className="flex-1 sm:flex-none flex items-center justify-center gap-1.5 text-xs font-bold bg-slate-800 text-white px-3 py-2 rounded-lg hover:bg-slate-700 transition-colors shadow-sm uppercase"
            >
              <Printer size={14} />
              <span>Cetak</span>
            </button>

            <button 
              onClick={handleExportCSV}
              className="flex-1 sm:flex-none flex items-center justify-center gap-1.5 text-xs font-bold bg-green-700 text-white px-3 py-2 rounded-lg hover:bg-green-800 transition-colors shadow-sm uppercase"
            >
              <FileSpreadsheet size={14} />
              <span>Excel</span>
            </button>
            
            <a 
              href={GOOGLE_DRIVE_FOLDER_URL}
              target="_blank"
              rel="noopener noreferrer"
              className="flex-1 sm:flex-none flex items-center justify-center gap-1.5 text-xs font-bold bg-blue-700 text-white px-3 py-2 rounded-lg hover:bg-blue-800 transition-colors shadow-sm uppercase"
            >
              <ExternalLink size={14} />
              <span>Drive</span>
            </a>
          </div>
        </div>

        <div className="relative w-full">
          <Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" />
          <input 
            type="text" 
            placeholder="Cari lokasi atau petugas..." 
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="w-full pl-9 pr-4 py-2 bg-slate-100 border-none rounded-lg text-sm text-slate-900 focus:ring-2 focus:ring-slate-500 font-medium"
          />
        </div>
      </div>

      {/* List */}
      <div className="space-y-3">
        {filteredLogs.length === 0 ? (
          <div className="text-center py-12 bg-white rounded-xl border border-dashed border-slate-300">
            <p className="text-slate-400 font-medium">Belum ada data patroli tersimpan.</p>
          </div>
        ) : (
          filteredLogs.map(log => (
            <div key={log.id} className="bg-white rounded-xl p-4 shadow-sm border border-slate-200 flex gap-4 transition-transform hover:scale-[1.01]">
              <div className="w-24 h-24 flex-shrink-0">
                <img 
                  src={log.imageUrl} 
                  alt="Evidence" 
                  className="w-full h-full object-cover rounded-lg bg-slate-200 border border-slate-100"
                />
              </div>
              
              <div className="flex-1 min-w-0 flex flex-col justify-between">
                <div>
                  <div className="flex justify-between items-start mb-1">
                    <h3 className="font-bold text-slate-900 truncate uppercase">{log.locationName}</h3>
                    <span className="text-[10px] text-slate-500 bg-slate-100 px-1.5 py-0.5 rounded font-mono border border-slate-200">
                      {new Date(log.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                    </span>
                  </div>
                  
                  <div className="flex items-center gap-2 text-xs text-slate-600 mb-1 font-medium">
                    <User size={12} />
                    <span>{log.guardName}</span>
                  </div>
                  
                  {log.aiAnalysis && (
                    <div className="mt-1">
                       <span className={`text-[10px] px-2 py-0.5 rounded font-bold border uppercase tracking-wide ${
                         log.aiAnalysis.status === PatrolStatus.SECURE ? 'bg-green-50 text-green-800 border-green-200' : 
                         'bg-red-50 text-red-800 border-red-200'
                       }`}>
                         AI: {log.aiAnalysis.status}
                       </span>
                    </div>
                  )}
                  
                  {log.coordinates && (
                    <div className="flex items-center gap-1 text-[10px] text-slate-400 mt-1">
                      <MapPin size={10} />
                      <span>{log.coordinates.latitude.toFixed(5)}, {log.coordinates.longitude.toFixed(5)}</span>
                    </div>
                  )}
                </div>

                <div className="flex justify-between items-end mt-2">
                  <p className="text-xs text-slate-500 truncate w-full pr-4 italic">
                    {log.aiAnalysis?.summary || log.notes || "Tidak ada catatan"}
                  </p>
                  <button className="text-slate-600 hover:text-slate-900 p-1">
                    <Eye size={16} />
                  </button>
                </div>
              </div>
            </div>
          ))
        )}
      </div>
    </div>
  );
};